### ISSUE TITLE
Widget Properties dose not work

### ISSUE THREAD

**Issue by skynovice** [zlkrnynkrc/flutterwidgetlistedit#1]
Widget Properties dose not work
<img width="506" alt="image" src="https://github.com/user-attachments/assets/a2a20d7e-5eb7-46ba-9378-fc7f09515b12">

**Comment by zlkrnynkrc** [comment]
İs it only on container.if only on container i will check on free time.if on any widget you should look dart analysis server is exist. if exist  you may need to manually add path to plugin settings.

**Comment by skynovice** [comment]
It all, not only container
thanks for good work.

**Comment by zlkrnynkrc** [comment]
> It all, not only container thanks for good work.

found bug it is with windows pc . im using linux cant run on windows or on mac. fixed and improved with new version here :[visual flutter](https://open-vsx.org/extension/zlkrnynkrc/visualeditflutter) download and install vsix file for vscode
